language: node_js
node_js:
- 6
before_script:
- npm install
script:
- npm test
notifications:
  slack:
    secure: T1DBE66nVZ1si++MHLjkdn7YMo+Komjq8AKSA/udQBqNvOK1C7AZ3YuwFJoA3phkwX0hzAZ4sRlGMJj2AB9QUw109/3vqfPd9fafhIY4ynNVXNRW0uiXCkoT+L0KcLwt/GBj5zfep53mwi7uPgnUvsAXRjXmofgUi/p3MJYjjVE=
